version: '3.9'

services:
  noteapp-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080

volumes:
  data: